In [213]:
import pandas as pd
import numpy as np

# 1) загрузка данных

In [321]:
df = pd.read_csv('data_set_csv.csv',sep=';')
df.head()

ID LIMIT_BAL     SEX EDUCATION MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1     20000  female  bachelor  married   24      2      2     -1     -1   
1   2    120000  female  bachelor   single   26     -1      2      0      0   
2   3     90000  female  bachelor   single   34      0      0      0      0   
3   4     50000  female  bachelor  married   37      0      0      0      0   
4   5     50000    male  bachelor  married   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2 PAY_AMT3 PAY_AMT4  \
0  ...          0          0         0        0      689        0        0   
1  ...       3272       3455      3261        0     1000     1000     1000   
2  ...      14331      14948     15549     1518     1500     1000     1000   
3  ...      28314      28959     29547     2000     2019     1200     1100   
4  ...      20940      19146     19131     2000    36681    10000     9000   

  PAY_AMT5 PAY_AMT6 target  
0        0        0      1  
1        0     2000      1  
2     1000     5000      0  
3     1069     1000      0  
4      689      679      0  

[5 rows x 25 columns]

# 2) чистка данных


In [322]:
# Нужно поменять текстовые значения на числовые 
df.update(df['SEX'].map({'female':0,'male':1}))
df = df.dropna()
df.update(df['MARRIAGE'].map({'single':0,'married':1,'divorced':2}))
df.update(df['EDUCATION'].map({'high school':0,
                             'graduate school':1,
                             'college':2,
                             'bachelor':3,
                             'magistracy':4,
                             'doctoral studies':5}))
# limit_bal стринговое поле и там есть цифры которые имеют степень Е
df.update(df['LIMIT_BAL'].map({'1,00E+05':'100000',
                             '2,00E+05':'200000',
                             '3,00E+05':'300000',
                             '4,00E+05':'400000',
                             '5,00E+05':'500000',
                             '6,00E+05':'600000',
                             '7,00E+05':'700000',
                             '8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

############################################################################################################

df.update(df['BILL_AMT1'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['BILL_AMT2'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['BILL_AMT3'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['BILL_AMT4'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['BILL_AMT5'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['BILL_AMT6'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

############################################################################################################


df.update(df['PAY_AMT1'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['PAY_AMT2'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['PAY_AMT3'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['PAY_AMT4'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['PAY_AMT5'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

df.update(df['PAY_AMT6'].map({'1,00E+05':'100000','2,00E+05':'200000','3,00E+05':'300000','4,00E+05':'400000',
                             '5,00E+05':'500000','6,00E+05':'600000','7,00E+05':'700000','8,00E+05':'800000',
                             '1,00E+06':'1000000'}))

############################################################################################################


In [291]:
#df['LIMIT_BAL'].unique()
df.head()

ID LIMIT_BAL SEX EDUCATION MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  ...  \
0   1     20000   0         3        1   24      2      2     -1     -1  ...   
1   2    120000   0         3        0   26     -1      2      0      0  ...   
2   3     90000   0         3        0   34      0      0      0      0  ...   
3   4     50000   0         3        1   37      0      0      0      0  ...   
4   5     50000   1         3        1   57     -1      0     -1      0  ...   

   BILL_AMT4  BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2 PAY_AMT3 PAY_AMT4  \
0          0          0         0        0      689        0        0   
1       3272       3455      3261        0     1000     1000     1000   
2      14331      14948     15549     1518     1500     1000     1000   
3      28314      28959     29547     2000     2019     1200     1100   
4      20940      19146     19131     2000    36681    10000     9000   

  PAY_AMT5 PAY_AMT6 target  
0        0        0      1  
1        0     2000      1  
2     1000     5000      0  
3     1069     1000      0  
4      689      679      0  

[5 rows x 25 columns]

In [332]:
X = df.iloc[:,:24]
y = df['target']

In [333]:
#X['EDUCATION'].unique()
#X.info()
X.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [334]:
X[X['PAY_AMT1']=='1,00E+05']

Empty DataFrame
Columns: [ID, LIMIT_BAL, SEX, EDUCATION, MARRIAGE, AGE, PAY_0, PAY_2, PAY_3, PAY_4, PAY_5, PAY_6, BILL_AMT1, BILL_AMT2, BILL_AMT3, BILL_AMT4, BILL_AMT5, BILL_AMT6, PAY_AMT1, PAY_AMT2, PAY_AMT3, PAY_AMT4, PAY_AMT5, PAY_AMT6]
Index: []

[0 rows x 24 columns]

# 3) Строим алгоритм Логистической регрессии 

In [335]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

### 3.1)строим крос-валидацию для увелечение обучения 

In [336]:
#делим на 5 частей и делаем шафл перед разбивкой чтобы не было разделения по классам
kf = KFold(n_splits=5,shuffle=True,random_state=241)

In [337]:
X_train , X_test , y_train , y_test = train_test_split(X,y)

In [376]:
clf = LogisticRegression(solver='liblinear',C=10000)

In [377]:
 clf.fit(X_train,y_train)


LogisticRegression(C=10000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [378]:
cvs = cross_val_score(clf,X_train,y_train,cv=kf)
np.mean(cvs)

0.7779412679646014

In [379]:
cvs = cross_val_score(clf,X_test,y_test,cv=kf)
np.mean(cvs)

0.7805672843012228

In [359]:
pd.value_counts(y)

0    23301
1     6631
Name: target, dtype: int64

In [386]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

In [384]:
q =  clf.fit(X_train,y_train)
qr = q.predict(X_test)


In [385]:
precision_recall_fscore_support(y_test,qr)

/Users/a1/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.77976747, 0.        ]),
 array([1., 0.]),
 array([0.8762577, 0.       ]),
 array([5835, 1648]))

In [387]:
accuracy_score(y_test,qr)

0.779767472938661

In [388]:
len(y_test)

7483

7483